name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  call-deploy:
    uses: digitaledsafety/workflows/.github/workflows/reusable-deploy.yml@main
    with:
      ruby-version: '3.2' # Example of overriding a default
      node-version: '20'
